# fly.toml file generated for log-forwarder on 2022-02-15T19:52:09+07:00

app = "log-forwarder"

[env]
  ORG = "doyobi"
  QUEUE = "log-forwarder"
  SUBJECT = "logs.>"

[metrics]
  port = 9598
  path = "/metrics"
